import urllib.parse

def placeholder_image_url(name, w=320, h=180):
    # uses picsum.photos as placeholder image service (unique per name)
    seed = urllib.parse.quote_plus(name)
    print(seed)
    return f"https://picsum.photos/seed/{name}/{w}/{h}"

POIS_BY_STATE = {
    "West Bengal": {
    "Kolkata": [
            {"name":"Victoria Memorial", "lat":22.5448, "lon":88.3426, "duration":1.5,
             "description":"Grand marble building dedicated to Queen Victoria with museum exhibits.",
             "tags":["historical","cultural"],
             "image": placeholder_image_url("Victoria Memorial Kolkata")},
            {"name":"Indian Museum", "lat":22.5626, "lon":88.3514, "duration":2.0,
             "description":"India’s oldest museum with rare artifacts and natural history collections.",
             "tags":["historical","cultural","family"],
             "image": placeholder_image_url("Indian Museum Kolkata")},
            {"name":"Howrah Bridge", "lat":22.5850, "lon":88.3468, "duration":0.5,
             "description":"Iconic cantilever bridge over the Hooghly River.",
             "tags":["historical","romantic"],
             "image": placeholder_image_url("Howrah Bridge Kolkata")},
            {"name":"Dakshineswar Kali Temple", "lat":22.6547, "lon":88.3570, "duration":1.5,
             "description":"Famous riverside temple dedicated to Goddess Kali.",
             "tags":["spiritual","cultural"],
             "image": placeholder_image_url("Dakshineswar Kali Temple Kolkata")},
            {"name":"Belur Math", "lat":22.6325, "lon":88.3560, "duration":2.0,
             "description":"Global headquarters of Ramakrishna Mission with serene architecture.",
             "tags":["spiritual","relaxation"],
             "image": placeholder_image_url("Belur Math Kolkata")},
            {"name":"Marble Palace", "lat":22.5834, "lon":88.3656, "duration":1.5,
             "description":"19th-century mansion with sculptures, paintings, and a private zoo.",
             "tags":["historical","cultural"],
             "image": placeholder_image_url("Marble Palace Kolkata")},
            {"name":"Science City", "lat":22.5390, "lon":88.4029, "duration":2.5,
             "description":"Interactive science museum with space theatre and exhibits.",
             "tags":["family","cultural"],
             "image": placeholder_image_url("Science City Kolkata")},
            {"name":"Alipore Zoo", "lat":22.5362, "lon":88.3300, "duration":2.0,
             "description":"India’s oldest zoological garden with diverse animal species.",
             "tags":["family","relaxation"],
             "image": placeholder_image_url("Alipore Zoo Kolkata")},
            {"name":"Eden Gardens", "lat":22.5646, "lon":88.3433, "duration":1.0,
             "description":"Historic cricket stadium and home of Indian cricket history.",
             "tags":["historical","family"],
             "image": placeholder_image_url("Eden Gardens Kolkata")},
            {"name":"South Park Street Cemetery", "lat":22.5461, "lon":88.3631, "duration":1.0,
             "description":"Colonial-era cemetery with Gothic tombs and quiet ambience.",
             "tags":["historical","romantic"],
             "image": placeholder_image_url("South Park Street Cemetery Kolkata")},
            {"name":"Kalighat Kali Temple", "lat":22.5203, "lon":88.3379, "duration":1.5,
             "description":"One of the 51 Shakti Peethas, dedicated to Goddess Kali.",
             "tags":["spiritual","cultural"],
             "image": placeholder_image_url("Kalighat Kali Temple Kolkata")},
            {"name":"Birla Planetarium", "lat":22.5441, "lon":88.3495, "duration":1.0,
             "description":"Dome-shaped planetarium with daily astronomy shows.",
             "tags":["family","cultural"],
             "image": placeholder_image_url("Birla Planetarium Kolkata")},
            {"name":"Nicco Park", "lat":22.5707, "lon":88.4204, "duration":3.0,
             "description":"Amusement park with rides, water slides, and attractions.",
             "tags":["family","adventure"],
             "image": placeholder_image_url("Nicco Park Kolkata")},
            {"name":"Birla Mandir", "lat":22.5416, "lon":88.3702, "duration":1.0,
             "description":"Beautifully carved white marble temple dedicated to Lord Krishna.",
             "tags":["spiritual","romantic"],
             "image": placeholder_image_url("Birla Mandir Kolkata")},
            {"name":"Princep Ghat", "lat":22.5467, "lon":88.3349, "duration":1.0,
             "description":"Picturesque riverside ghat with colonial architecture.",
             "tags":["romantic","relaxation"],
             "image": placeholder_image_url("Princep Ghat Kolkata")},
            {"name":"St. Paul’s Cathedral", "lat":22.5446, "lon":88.3483, "duration":1.0,
             "description":"Anglican cathedral known for Gothic architecture.",
             "tags":["historical","cultural","spiritual"],
             "image": placeholder_image_url("St. Paul’s Cathedral Kolkata")},
            {"name":"Jorasanko Thakur Bari", "lat":22.5853, "lon":88.3632, "duration":1.5,
             "description":"Ancestral home of Rabindranath Tagore, now a museum.",
             "tags":["historical","cultural"],
             "image": placeholder_image_url("Jorasanko Thakur Bari Kolkata")},
            {"name":"Town Hall", "lat":22.5671, "lon":88.3471, "duration":1.0,
             "description":"Colonial-era building hosting exhibitions and events.",
             "tags":["historical","cultural"],
             "image": placeholder_image_url("Town Hall Kolkata")},
            {"name":"Eco Park", "lat":22.6036, "lon":88.4650, "duration":3.0,
             "description":"Large urban park with boating, gardens, and themed zones.",
             "tags":["family","relaxation","adventure"],
             "image": placeholder_image_url("Eco Park Kolkata")},
            {"name":"Mother House", "lat":22.5379, "lon":88.3634, "duration":1.0,
             "description":"Home and tomb of Mother Teresa, now a pilgrimage site.",
             "tags":["spiritual","historical"],
             "image": placeholder_image_url("Mother House Kolkata")},
            {"name":"College Street (Boi Para)", "lat":22.5747, "lon":88.3634, "duration":1.5,
             "description":"Asia’s largest book market, lined with old shops and stalls.",
             "tags":["cultural","family"],
             "image": placeholder_image_url("College Street Kolkata")},
            {"name":"Kumartuli", "lat":22.5992, "lon":88.3689, "duration":1.0,
             "description":"Traditional potters’ quarter where Durga idols are crafted.",
             "tags":["cultural","historical"],
             "image": placeholder_image_url("Kumartuli Kolkata")},
            {"name":"Rabindra Sadan", "lat":22.5428, "lon":88.3510, "duration":1.0,
             "description":"Cultural hub for Bengali theatre, film, and art.",
             "tags":["cultural","family"],
             "image": placeholder_image_url("Rabindra Sadan Kolkata")},
            {"name":"Nakhoda Mosque", "lat":22.5750, "lon":88.3629, "duration":1.0,
             "description":"Largest mosque in Kolkata with striking red sandstone structure.",
             "tags":["spiritual","historical"],
             "image": placeholder_image_url("Nakhoda Mosque Kolkata")},
            {"name":"Metropolitan Building", "lat":22.5678, "lon":88.3506, "duration":0.5,
             "description":"Colonial-style building at Esplanade, now housing shops.",
             "tags":["historical","cultural"],
             "image": placeholder_image_url("Metropolitan Building Kolkata")},
             {"name":"Salt Lake Stadium", "lat":22.5684, "lon":88.4139, "duration":1.5,
     "description":"One of the largest football stadiums in the world.",
     "tags":["family","historical"],
     "image": placeholder_image_url("Salt Lake Stadium Kolkata")},
    
    {"name":"Shobhabazar Rajbari", "lat":22.5996, "lon":88.3683, "duration":1.0,
     "description":"18th-century palace known for its Durga Puja celebrations.",
     "tags":["historical","cultural"],
     "image": placeholder_image_url("Shobhabazar Rajbari Kolkata")},
    
    {"name":"Botanical Garden (Acharya Jagadish Chandra Bose Garden)", "lat":22.5371, "lon":88.2776, "duration":2.0,
     "description":"Historic garden with a giant Banyan Tree and rare plant species.",
     "tags":["relaxation","family","nature"],
     "image": placeholder_image_url("Botanical Garden Kolkata")},
    
    {"name":"National Library of India", "lat":22.5351, "lon":88.3428, "duration":1.5,
     "description":"India’s largest library with a massive collection of books and manuscripts.",
     "tags":["cultural","historical"],
     "image": placeholder_image_url("National Library Kolkata")},
    
    {"name":"Aquatica Water Park", "lat":22.5647, "lon":88.4826, "duration":3.0,
     "description":"Popular water park with slides, pools, and wave rides.",
     "tags":["family","adventure","relaxation"],
     "image": placeholder_image_url("Aquatica Water Park Kolkata")},
    
    {"name":"Birla Industrial & Technological Museum", "lat":22.5421, "lon":88.3637, "duration":2.0,
     "description":"Interactive science and technology museum for children and adults.",
     "tags":["family","educational"],
     "image": placeholder_image_url("Birla Industrial Technological Museum Kolkata")},
    
    {"name":"Park Street", "lat":22.5526, "lon":88.3514, "duration":2.0,
     "description":"Famous nightlife and dining hub of Kolkata.",
     "tags":["cultural","romantic","family"],
     "image": placeholder_image_url("Park Street Kolkata")},
    
    {"name":"New Market (Hogg Market)", "lat":22.5603, "lon":88.3521, "duration":2.0,
     "description":"Colonial-era marketplace for clothes, food, and handicrafts.",
     "tags":["shopping","cultural"],
     "image": placeholder_image_url("New Market Kolkata")},
    
    {"name":"Quest Mall", "lat":22.5393, "lon":88.3650, "duration":2.0,
     "description":"Modern luxury shopping mall with international brands and dining.",
     "tags":["shopping","family"],
     "image": placeholder_image_url("Quest Mall Kolkata")},
    
    {"name":"Millennium Park", "lat":22.5718, "lon":88.3493, "duration":1.5,
     "description":"Riverside park with gardens, rides, and Hooghly River views.",
     "tags":["family","romantic","relaxation"],
     "image": placeholder_image_url("Millennium Park Kolkata")},
    
    {"name":"Swami Vivekananda’s Ancestral House", "lat":22.5851, "lon":88.3630, "duration":1.5,
     "description":"Birthplace and museum dedicated to Swami Vivekananda.",
     "tags":["spiritual","historical"],
     "image": placeholder_image_url("Swami Vivekananda House Kolkata")},
    
    {"name":"Rabindra Sarobar Lake", "lat":22.5146, "lon":88.3465, "duration":1.5,
     "description":"Serene artificial lake surrounded by gardens and walking paths.",
     "tags":["relaxation","romantic","family"],
     "image": placeholder_image_url("Rabindra Sarobar Lake Kolkata")},
    
    {"name":"Shaheed Minar", "lat":22.5675, "lon":88.3518, "duration":0.5,
     "description":"Historic monument originally built in memory of Major-General Ochterlony.",
     "tags":["historical","cultural"],
     "image": placeholder_image_url("Shaheed Minar Kolkata")},
    
    {"name":"Science College Observatory", "lat":22.5628, "lon":88.3712, "duration":1.0,
     "description":"Astronomical observatory for public stargazing and education.",
     "tags":["educational","family"],
     "image": placeholder_image_url("Science College Observatory Kolkata")},
    
    {"name":"Mother’s Wax Museum", "lat":22.6036, "lon":88.4650, "duration":1.5,
     "description":"Wax museum featuring life-size statues of global icons and celebrities.",
     "tags":["family","cultural"],
     "image": placeholder_image_url("Mother’s Wax Museum Kolkata")},
     {"name":"St. John’s Church", "lat":22.5702, "lon":88.3486, "duration":1.0,
     "description":"18th-century church with colonial architecture and historic tombs.",
     "tags":["historical","spiritual"],
     "image": placeholder_image_url("St. John’s Church Kolkata")},

    {"name":"Armenian Church of the Holy Nazareth", "lat":22.5748, "lon":88.3517, "duration":1.0,
     "description":"One of the oldest churches in Kolkata, dating back to 1724.",
     "tags":["historical","spiritual"],
     "image": placeholder_image_url("Armenian Church Kolkata")},

    {"name":"Mallick Ghat Flower Market", "lat":22.5853, "lon":88.3508, "duration":1.0,
     "description":"Bustling wholesale flower market near Howrah Bridge.",
     "tags":["cultural","shopping"],
     "image": placeholder_image_url("Mallick Ghat Flower Market Kolkata")},

    {"name":"Sealdah Market", "lat":22.5672, "lon":88.3744, "duration":1.0,
     "description":"Traditional market for daily essentials, food, and textiles.",
     "tags":["shopping","cultural"],
     "image": placeholder_image_url("Sealdah Market Kolkata")},

    {"name":"Dakshineswar Ghat", "lat":22.6535, "lon":88.3579, "duration":1.0,
     "description":"Sacred riverside ghat near Dakshineswar Kali Temple.",
     "tags":["spiritual","relaxation"],
     "image": placeholder_image_url("Dakshineswar Ghat Kolkata")},

    {"name":"Princep Memorial", "lat":22.5467, "lon":88.3347, "duration":0.5,
     "description":"Colonial memorial dedicated to James Prinsep near the riverbank.",
     "tags":["historical","romantic"],
     "image": placeholder_image_url("Princep Memorial Kolkata")},

    {"name":"James Prinsep House", "lat":22.5465, "lon":88.3345, "duration":0.5,
     "description":"Historic riverside pavilion popular for evening walks.",
     "tags":["relaxation","romantic"],
     "image": placeholder_image_url("James Prinsep House Kolkata")},

    {"name":"Raj Bhavan", "lat":22.5697, "lon":88.3505, "duration":1.0,
     "description":"Official residence of the Governor of West Bengal, built in 1803.",
     "tags":["historical","cultural"],
     "image": placeholder_image_url("Raj Bhavan Kolkata")},

    {"name":"General Post Office (GPO)", "lat":22.5712, "lon":88.3500, "duration":0.5,
     "description":"Iconic colonial-era building with a grand dome and Corinthian pillars.",
     "tags":["historical","cultural"],
     "image": placeholder_image_url("General Post Office Kolkata")},

    {"name":"Writers’ Building", "lat":22.5732, "lon":88.3522, "duration":0.5,
     "description":"Historic red building, former secretariat of West Bengal government.",
     "tags":["historical","cultural"],
     "image": placeholder_image_url("Writers’ Building Kolkata")},

    {"name":"Bankshall Court", "lat":22.5736, "lon":88.3530, "duration":0.5,
     "description":"Colonial-era court building representing British architecture.",
     "tags":["historical","cultural"],
     "image": placeholder_image_url("Bankshall Court Kolkata")},

    {"name":"Metcalfe Hall", "lat":22.5699, "lon":88.3507, "duration":1.0,
     "description":"19th-century building inspired by Greek temple architecture.",
     "tags":["historical","cultural"],
     "image": placeholder_image_url("Metcalfe Hall Kolkata")},

    {"name":"Town Hall Museum", "lat":22.5673, "lon":88.3470, "duration":1.0,
     "description":"Museum inside colonial Town Hall showcasing Kolkata’s history.",
     "tags":["historical","cultural"],
     "image": placeholder_image_url("Town Hall Museum Kolkata")},

    {"name":"Raja Rammohan Roy Memorial Museum", "lat":22.5609, "lon":88.3661, "duration":1.0,
     "description":"Memorial dedicated to the social reformer Raja Rammohan Roy.",
     "tags":["historical","cultural"],
     "image": placeholder_image_url("Raja Rammohan Roy Memorial Museum Kolkata")},

    {"name":"Tagore’s Statue (College Street)", "lat":22.5750, "lon":88.3640, "duration":0.5,
     "description":"Famous statue of Rabindranath Tagore at College Street.",
     "tags":["historical","cultural"],
     "image": placeholder_image_url("Tagore Statue Kolkata")},

    {"name":"Chowringhee", "lat":22.5556, "lon":88.3523, "duration":1.0,
     "description":"Bustling district with shops, hotels, and colonial-era buildings.",
     "tags":["cultural","shopping"],
     "image": placeholder_image_url("Chowringhee Kolkata")},

    {"name":"Maidan", "lat":22.5564, "lon":88.3522, "duration":2.0,
     "description":"Vast urban park known as the ‘lungs of Kolkata’.",
     "tags":["relaxation","family"],
     "image": placeholder_image_url("Maidan Kolkata")},

    {"name":"Race Course", "lat":22.5453, "lon":88.3480, "duration":1.0,
     "description":"Historic horse racing venue near Maidan.",
     "tags":["cultural","relaxation"],
     "image": placeholder_image_url("Race Course Kolkata")},

    {"name":"Fort William", "lat":22.5545, "lon":88.3421, "duration":1.5,
     "description":"18th-century fort built by the British, now under Indian Army.",
     "tags":["historical","cultural"],
     "image": placeholder_image_url("Fort William Kolkata")},

    {"name":"Elliot Park", "lat":22.5487, "lon":88.3525, "duration":1.0,
     "description":"Popular green park with walking paths and lawns.",
     "tags":["relaxation","family"],
     "image": placeholder_image_url("Elliot Park Kolkata")},

    {"name":"Shrine Basilica of the Holy Rosary (Bandel Church)", "lat":22.9253, "lon":88.3759, "duration":2.0,
     "description":"One of the oldest Christian churches in West Bengal, built by Portuguese.",
     "tags":["spiritual","historical"],
     "image": placeholder_image_url("Bandel Church Kolkata")},

    {"name":"Chintamoni Kar Bird Sanctuary", "lat":22.4178, "lon":88.4195, "duration":2.0,
     "description":"Sanctuary known for birdwatching and lush greenery.",
     "tags":["nature","relaxation"],
     "image": placeholder_image_url("Chintamoni Kar Bird Sanctuary Kolkata")},

    {"name":"Nazrul Mancha", "lat":22.5209, "lon":88.3645, "duration":1.5,
     "description":"Open-air auditorium for cultural shows and concerts.",
     "tags":["cultural","family"],
     "image": placeholder_image_url("Nazrul Mancha Kolkata")},

    {"name":"Academy of Fine Arts", "lat":22.5434, "lon":88.3490, "duration":1.5,
     "description":"Cultural center showcasing art exhibitions and performances.",
     "tags":["cultural","family"],
     "image": placeholder_image_url("Academy of Fine Arts Kolkata")},

    {"name":"Birla Academy of Art & Culture", "lat":22.5369, "lon":88.3646, "duration":1.5,
     "description":"Art museum housing Indian and international collections.",
     "tags":["cultural","historical"],
     "image": placeholder_image_url("Birla Academy of Art and Culture Kolkata")},

    {"name":"Kolkata Police Museum", "lat":22.5740, "lon":88.3680, "duration":1.0,
     "description":"Museum showcasing Kolkata Police’s history and archives.",
     "tags":["historical","cultural"],
     "image": placeholder_image_url("Kolkata Police Museum")},

    {"name":"Smaranika Tram Museum", "lat":22.5625, "lon":88.3510, "duration":1.0,
     "description":"Unique museum dedicated to Kolkata’s historic trams.",
     "tags":["historical","cultural"],
     "image": placeholder_image_url("Smaranika Tram Museum Kolkata")},

    {"name":"Science Exploratorium", "lat":22.5456, "lon":88.3632, "duration":2.0,
     "description":"Hands-on science learning center for children.",
     "tags":["educational","family"],
     "image": placeholder_image_url("Science Exploratorium Kolkata")}
],
        "Darjeeling": [
            {"name":"Tiger Hill", "lat":27.4189, "lon":88.2790, "duration":1.5, "description":"Sunrise views over Kanchenjunga.", "tags":["romantic","nature"], "image": placeholder_image_url("Tiger Hill Darjeeling")},
            {"name":"Darjeeling Toy Train", "lat":27.0380, "lon":88.2627, "duration":2.5, "description":"Heritage steam/rail experience.", "tags":["relaxation","family"], "image": placeholder_image_url("Toy Train Darjeeling")},
            {"name":"Batasia Loop", "lat":27.0369, "lon":88.2753, "duration":0.75, "description":"Scenic loop & memorial.", "tags":["relaxation"], "image": placeholder_image_url("Batasia Loop")},
            {"name":"Padmaja Naidu Himalayan Zoological Park", "lat":27.0335, "lon":88.2611, "duration":2.0, "description":"High-altitude conservation zoo.", "tags":["family","nature"], "image": placeholder_image_url("Himalayan Zoo Darjeeling")},
            {"name":"Tea Gardens (Happy Valley)", "lat":27.0642, "lon":88.2486, "duration":2.0, "description":"Tea estate tour & tasting.", "tags":["relaxation"], "image": placeholder_image_url("Happy Valley Tea Darjeeling")},
            {"name":"Japanese Peace Pagoda", "lat":27.0388, "lon":88.2436, "duration":0.75, "description":"Panoramic views and peace pagoda.", "tags":["relaxation","spiritual"], "image": placeholder_image_url("Peace Pagoda Darjeeling")},
            {"name":"Darjeeling Mall", "lat":27.0416, "lon":88.2604, "duration":1.0, "description":"Town center & shops.", "tags":["relaxation"], "image": placeholder_image_url("Darjeeling Mall")},
            {"name":"Observatory Hill", "lat":27.0411, "lon":88.2600, "duration":0.5, "description":"Small hill with views.", "tags":["relaxation"], "image": placeholder_image_url("Observatory Hill Darjeeling")},
            {"name":"Ghoom Monastery", "lat":27.0379, "lon":88.2473, "duration":0.75, "description":"Historic Buddhist monastery.", "tags":["spiritual","cultural"], "image": placeholder_image_url("Ghoom Monastery")},
            {"name":"Rock Garden & Ganga Maya Park", "lat":27.0362, "lon":88.2710, "duration":1.0, "description":"Terraced garden and park.", "tags":["family","relaxation"], "image": placeholder_image_url("Rock Garden Darjeeling")},
            {"name":"Himalayan Mountaineering Institute", "lat":27.0340, "lon":88.2575, "duration":1.5, "description":"Mountaineering museum & displays.", "tags":["cultural"], "image": placeholder_image_url("HMI Darjeeling")},
            {"name":"Chowrasta", "lat":27.0390, "lon":88.2622, "duration":0.75, "description":"Leisure stroll spot with shops.", "tags":["relaxation","family"], "image": placeholder_image_url("Chowrasta Darjeeling")}
        ],
        "Shantiniketan": [
            {"name":"Visva Bharati (Tagore's University)", "lat":23.6840, "lon":87.6806, "duration":2.5, "description":"Cultural university founded by Rabindranath Tagore.", "tags":["cultural"], "image": placeholder_image_url("Visva Bharati")},
            {"name":"Amar Kutir", "lat":23.6844, "lon":87.6788, "duration":1.0, "description":"Crafts cooperative and museum.", "tags":["cultural"], "image": placeholder_image_url("Amar Kutir")},
            {"name":"Shyamali", "lat":23.6855, "lon":87.6790, "duration":0.75, "description":"Historic residence & gallery.", "tags":["cultural"], "image": placeholder_image_url("Shyamali Shantiniketan")},
            {"name":"Rabinrasala", "lat":23.6846, "lon":87.6796, "duration":0.75, "description":"Artist cottages & galleries.", "tags":["cultural"], "image": placeholder_image_url("Rabinrasala")},
            {"name":"Bonophool", "lat":23.6868, "lon":87.6810, "duration":1.0, "description":"Local handicraft shops.", "tags":["cultural"], "image": placeholder_image_url("Bonophool")},
            {"name":"Poush Mela (seasonal)", "lat":23.6840, "lon":87.6806, "duration":3.0, "description":"Annual fair—seasonal highlight.", "tags":["cultural","family"], "image": placeholder_image_url("Poush Mela")}
        ]
    },
    "Delhi": {
        "New Delhi": [
            {"name":"Red Fort", "lat":28.6562, "lon":77.2410, "duration":2.0, "description":"17th-century Mughal fort.", "tags":["historical","cultural"], "image": placeholder_image_url("Red Fort Delhi")},
            {"name":"Qutub Minar", "lat":28.5244, "lon":77.1855, "duration":1.5, "description":"Tall minaret & complex.", "tags":["historical"], "image": placeholder_image_url("Qutub Minar")},
            {"name":"Humayun's Tomb", "lat":28.5933, "lon":77.2507, "duration":1.5, "description":"Precursor to the Taj Mahal.", "tags":["historical"], "image": placeholder_image_url("Humayun Tomb")},
            {"name":"India Gate & Rajpath", "lat":28.6129, "lon":77.2295, "duration":0.75, "description":"National war memorial & lawns.", "tags":["relaxation"], "image": placeholder_image_url("India Gate")},
            {"name":"Lotus Temple", "lat":28.5535, "lon":77.2588, "duration":1.0, "description":"Bahá'í House of Worship.", "tags":["spiritual"], "image": placeholder_image_url("Lotus Temple")},
            {"name":"Chandni Chowk Food Walk", "lat":28.6560, "lon":77.2300, "duration":2.5, "description":"Historic bazaars & street food.", "tags":["cultural","family"], "image": placeholder_image_url("Chandni Chowk")},
            {"name":"Akshardham Temple", "lat":28.6123, "lon":77.2772, "duration":2.0, "description":"Large modern temple complex.", "tags":["cultural"], "image": placeholder_image_url("Akshardham")},
            {"name":"Hauz Khas Village", "lat":28.5495, "lon":77.1964, "duration":2.0, "description":"Trendy cafes & deer park.", "tags":["relaxation"], "image": placeholder_image_url("Hauz Khas")},
            {"name":"National Museum", "lat":28.6090, "lon":77.2275, "duration":2.0, "description":"Large national collections.", "tags":["cultural"], "image": placeholder_image_url("National Museum Delhi")},
            {"name":"Connaught Place", "lat":28.6335, "lon":77.2167, "duration":1.5, "description":"Shopping & restaurants hub.", "tags":["relaxation"], "image": placeholder_image_url("Connaught Place")},
            {"name":"Jama Masjid", "lat":28.6503, "lon":77.2334, "duration":1.0, "description":"One of India's largest mosques.", "tags":["cultural"], "image": placeholder_image_url("Jama Masjid")},
            {"name":"Gandhi Smriti", "lat":28.6144, "lon":77.2100, "duration":1.0, "description":"Memorial to Mahatma Gandhi.", "tags":["historical","cultural"], "image": placeholder_image_url("Gandhi Smriti")}
        ],
        "Gurgaon": [
            {"name":"Kingdom of Dreams", "lat":28.4996, "lon":77.0794, "duration":3.0, "description":"Entertainment and musicals.", "tags":["family","cultural"], "image": placeholder_image_url("Kingdom of Dreams")},
            {"name":"Cyber Hub", "lat":28.5036, "lon":77.0880, "duration":1.5, "description":"Dining and nightlife hub.", "tags":["relaxation"], "image": placeholder_image_url("Cyber Hub Gurgaon")},
            {"name":"Sultanpur National Park", "lat":28.4692, "lon":77.0401, "duration":2.0, "description":"Bird sanctuary.", "tags":["nature","relaxation"], "image": placeholder_image_url("Sultanpur Park")},
            {"name":"Damdama Lake", "lat":28.3460, "lon":77.1747, "duration":3.0, "description":"Water activities & picnics.", "tags":["adventure","relaxation"], "image": placeholder_image_url("Damdama Lake")},
            {"name":"Leisure Valley Park", "lat":28.4954, "lon":77.0821, "duration":1.0, "description":"Open lawns & seasonal events.", "tags":["relaxation"], "image": placeholder_image_url("Leisure Valley")}
        ],
        "Noida": [
            {"name":"Worlds of Wonder (Water & Amusement Park)", "lat":28.5863, "lon":77.3040, "duration":4.0, "description":"Family amusement park.", "tags":["family"], "image": placeholder_image_url("Worlds of Wonder Noida")},
            {"name":"Dilli Haat - Noida", "lat":28.5721, "lon":77.3215, "duration":1.5, "description":"Traditional crafts & food stalls.", "tags":["cultural"], "image": placeholder_image_url("Dilli Haat Noida")},
            {"name":"Botanical Garden, Noida", "lat":28.5993, "lon":77.3262, "duration":1.5, "description":"Green space & trails.", "tags":["relaxation"], "image": placeholder_image_url("Botanical Garden Noida")},
            {"name":"Okhla Bird Sanctuary", "lat":28.5451, "lon":77.3095, "duration":2.0, "description":"Wetland sanctuary for birds.", "tags":["nature"], "image": placeholder_image_url("Okhla Bird Sanctuary")}
        ]
    },
    "Uttar Pradesh": {
        "Agra": [
            {"name":"Taj Mahal", "lat":27.1751, "lon":78.0421, "duration":2.5, "description":"World-famous white marble mausoleum.", "tags":["historical","romantic"], "image": placeholder_image_url("Taj Mahal")},
            {"name":"Agra Fort", "lat":27.1794, "lon":78.0211, "duration":1.5, "description":"Red sandstone fortress.", "tags":["historical"], "image": placeholder_image_url("Agra Fort")},
            {"name":"Mehtab Bagh", "lat":27.1759, "lon":78.0409, "duration":1.0, "description":"Garden with Taj views at sunset.", "tags":["romantic","relaxation"], "image": placeholder_image_url("Mehtab Bagh")},
            {"name":"Itmad-ud-Daulah (Baby Taj)", "lat":27.1594, "lon":78.0468, "duration":1.0, "description":"Marble tomb with inlay work.", "tags":["historical"], "image": placeholder_image_url("Baby Taj")},
            {"name":"Local Markets (Sadar Bazaar)", "lat":27.1812, "lon":78.0081, "duration":1.5, "description":"Shopping & street food.", "tags":["cultural"], "image": placeholder_image_url("Sadar Bazaar Agra")}
        ],
        "Varanasi": [
            {"name":"Dashashwamedh Ghat", "lat":25.3176, "lon":82.9739, "duration":1.5, "description":"Ganga aarti at sunset.", "tags":["spiritual","cultural"], "image": placeholder_image_url("Dashashwamedh Ghat")},
            {"name":"Boat Ride on Ganga", "lat":25.3176, "lon":82.9739, "duration":1.0, "description":"River sunrise/sunset excursions.", "tags":["spiritual","romantic"], "image": placeholder_image_url("Boat Ride Varanasi")},
            {"name":"Sarnath", "lat":25.3910, "lon":83.0106, "duration":2.0, "description":"Buddhist archaeological site.", "tags":["historical","spiritual"], "image": placeholder_image_url("Sarnath")},
            {"name":"Banaras Hindu University (BHU) & Temple", "lat":25.2677, "lon":82.9868, "duration":1.5, "description":"Historic university campus.", "tags":["cultural"], "image": placeholder_image_url("BHU Varanasi")}
        ],
        "Lucknow": [
            {"name":"Bara Imambara", "lat":26.8467, "lon":80.9462, "duration":1.5, "description":"Architectural marvel with labyrinth.", "tags":["historical"], "image": placeholder_image_url("Bara Imambara")},
            {"name":"Rumi Darwaza", "lat":26.8462, "lon":80.9464, "duration":0.5, "description":"Iconic Lucknow gateway.", "tags":["cultural"], "image": placeholder_image_url("Rumi Darwaza")},
            {"name":"Hazratganj Market", "lat":26.8466, "lon":80.9470, "duration":1.0, "description":"Shopping & cafes.", "tags":["relaxation"], "image": placeholder_image_url("Hazratganj")},
            {"name":"British Residency", "lat":26.8407, "lon":80.9115, "duration":1.0, "description":"Historic ruins & gardens.", "tags":["historical"], "image": placeholder_image_url("British Residency Lucknow")}
        ]
    }
}
